config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get '/tracker' => 'user#index'

  devise_for :users, controllers: { omniauth_callbacks: :omniauth_callbacks }

end

app/models/user.rb
require 'fitgem'
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:fitbit]

  def update_with_fitbit_oauth(auth)
    auth_token = auth.credentials.token
    auth_secret = auth.credentials.secret
    self.token = auth_token
    self.uid = auth.uid
    self.secret = auth_secret
    self.save
  end

  def get_client
    Fitgem::Client.new(user_id: self.uid, consumer_key: "bac7a823979b4dddb95cd3cb265ab135", consumer_secret: "84ada8354c1043e9b68d3200047b611c", token: self.token, secret: self.secret)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def fitbit
    current_user.update_with_fitbit_oauth(request.env["omniauth.auth"])
    sign_in_and_redirect current_user, :event => :authentication
    set_flash_message(:notice, :success, :kind => "Fitbit") if is_navigational_format?
  end
end

app/controllers/token_controller.rb
class TokenController < ApplicationController
  def edit
    user = User.get_token(request.env["omniauth.auth"])
    redirect_to :back
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :authenticate_user!
  def index

    if current_user.token.present?

      client = current_user.get_client

      @steps = client.activity_on_date_range('steps', 6.days.ago, Time.now)
      gon.steps = @steps.fetch("activities-steps")


      @calories = client.activity_on_date_range('calories', 6.days.ago, Time.now)
      gon.calories = @calories.fetch("activities-calories")

      @distance = client.activity_on_date_range('distance', 6.days.ago, Time.now)
      gon.distance = @distance.fetch("activities-distance")
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/token_helper.rb
module TokenHelper
end

app/helpers/tracker_helper.rb
module TrackerHelper
end

app/helpers/trackers_helper.rb
module TrackersHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/home/index.html.haml
#main_page_container
  .row
    #text_wrap
      #about
        %h2#specf_about What we do:
        %br/
        %h3 SpyMD is a simple, fast interface for quickly comparing personal Fitbit data against recommended amounts.
        %br/
        %h3 With our help there is no longer a need to download heavy apps for a quick glance at your health statistics!
      #text_overlay
        %h1#head Spy MD
        #logo
          =image_tag "Inverse2.png"
        %h4#sub_text Tracking fitness is now easier than ever!
  -# .row
    -# %h2#tagline Get started today

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "Spy MD"
    = stylesheet_link_tag    "application"
    =stylesheet_link_tag     "http://fonts.googleapis.com/css?family=Lato"
    = include_gon
    = javascript_include_tag "vendor/modernizr"
    = javascript_include_tag "application"
    = javascript_include_tag "http://code.highcharts.com/highcharts.js"

    = csrf_meta_tags

  %body
    %div.sticky
      %nav.top-bar{"data-topbar" => "", :role => "navigation"}
        %ul.title-area
          %li.name
            %h1
              =image_tag "spyCrossInverse.jpg", class: "logo", id: "thumbnail"
          %li.toggle-topbar.menu-icon
            %a{:href => "root_path"}
        %section.top-bar-section
          %ul.left
            %li.spy Spy MD
            %li
              =link_to "Home", root_path
            %li
              - if user_signed_in?
                =link_to "Tracker", tracker_path
          %ul.right
            - if user_signed_in?
              %li#email
                =link_to "#{current_user.email}", edit_user_registration_path
              %li
                =link_to "Sign Out", destroy_user_session_path, method: :DELETE
            - else
              %li
                =link_to "Login", new_user_session_path
              %li
                =link_to "Sign Up", new_user_registration_path
    - if notice
      .alert-box.success= notice
    - if alert
      .alert-box.alert= alert
    = yield

app/views/user/index.html.haml
#tracker_container
  - if current_user.token.nil? && current_user.secret.nil? && current_user.uid.nil?
    #text
      %h4 Uh-oh! Your account hasn't been linked yet! Don't worry, we'll help you out.
      %h4 Please click the link below to set up account:
      = link_to "Link account", user_omniauth_authorize_path(:fitbit)
  -# - else
  #massive_container
    :javascript
      function showOrHide(chart){
        console.log(chart+"_container");
        $('.chart').removeClass("active");
        $('.chart').addClass("hidden");
        $("#"+chart+"_container").removeClass("hidden");
        $("#"+chart+"_container").addClass("active");
      };
    #button_container
      .button#steps{:onclick => "showOrHide('step')"} Steps
      .button#calories{:onclick => "showOrHide('calories')"} Calories
      .button#distance{:onclick => "showOrHide('distance')"} Distance
      -# .button#goals{:onclick => "showOrHide('goals')"} Goals

    #step_container.chart.active
      :javascript
        var t = new Date();
        var today = t.getDay();
        $('#step_container').highcharts({
          chart: {
            type: 'area'
          },
          title: {
            text: 'Weekly Steps'
          },
          xAxis: {
            type: "datetime",
            labels: {
              formatter: function(){
                return Highcharts.dateFormat('%a', this.value);
              }
            },
            tickPixelInterval: 200,
            title: {
              text: 'Days this week'
            }
          },
          yAxis: {
            title: {
              text: 'Total Steps'
            }
          },
          series: [{
            name: 'Your Steps',
            pointInterval: 24 * 3600 * 1000,
            //data: [7900, 8000, 8100, 8500, 7500, 7000, 9000],
            data: gon.steps.map(function(data){return Number(data.value)}),
            color:'#51de98',
            zIndex:2,
          }, {
            name: 'Recommended Steps',
            pointInterval: 24 * 3600 * 1000,
            data: [8000, 8000, 8000, 8000, 8000, 8000, 8000],
            color: '#17367e',
            zIndex:1,
          }]
        });

        console.log(gon.steps);

    #calories_container.chart.hidden
      :javascript
        var t = new Date();
        var today = t.getDay();
        $('#calories_container').highcharts({
          chart: {
            type: 'area'
          },
          title: {
            text: 'Weekly Calories'
          },
          xAxis: {
            type: "datetime",
            tickPixelInterval: 200,
            labels: {
              formatter: function(){
                return Highcharts.dateFormat('%a', this.value);
              }
            },
            title: {
              text: 'Days this week'
            }
          },
          yAxis: {
            title: {
              text: 'Total Calories'
            }
          },
          series: [{
            name: 'Your Calories',
            pointInterval: 24 * 3600 * 1000,
            // data: [2900, 1800, 2000, 2500, 3500, 3000, 2300],
            data: gon.calories.map(function(data){return Number(data.value)}),
            color: '#1cab2b',
            zIndex:4,
          }, {
            name: "Male's Recommended Calories",
            pointInterval: 24 * 3600 * 1000,
            data: [2500, 2500, 2500, 2500, 2500, 2500, 2500],
            color: '#1433fa',
            zIndex: 2,
          }, {
            name: "Female's Recommended Calories",
            pointInterval: 24 * 3600 * 1000,
            data: [2000, 2000, 2000, 2000, 2000, 2000, 2000],
            color: '#fff304',
            zIndex: 3,
            }]
        });
    #distance_container.chart.hidden
      :javascript
        var t = new Date();
        var today = t.getDay();
        $('#distance_container').highcharts({
          chart: {
            type: 'area'
          },
          title: {
            text: 'Distance Travelled'
          },
          xAxis: {
            type: "datetime",
            labels: {
              formatter: function(){
                return Highcharts.dateFormat('%a', this.value);
              }
            },
            tickPixelInterval: 200,
            title: {
              text: 'Days this week'
            }
          },
          yAxis: {
            title: {
              text: 'Total Miles'
            }
          },
          series: [{
            name: 'Your Distance',
            pointInterval: 24 * 3600 * 1000,
            // data: [7900, 8000, 8100, 8500, 7500, 7000, 9000],
            data: gon.distance.map(function(data){return Number(data.value)}),
            color: '#1cab2b',
            zIndex:1,
            }]
        });
    -# #goals_container.chart.hidden
    -#   :javascript
    -#     var t = new Date();
    -#     var today = t.getDay();
    -#     $('#goals_container').highcharts({
    -#       chart: {
    -#         type: 'area'
    -#       },
    -#       title: {
    -#         text: 'Personal Goals'
    -#       },
    -#       xAxis: {
    -#         type: "datetime",
    -#         labels: {
    -#           formatter: function(){
    -#             return Highcharts.dateFormat('%a', this.value);
    -#           }
    -#         },
    -#         tickPixelInterval: 50,
    -#         title: {
    -#           text: 'Days this week'
    -#         }
    -#       },
    -#       yAxis: {
    -#         title: {
    -#           text: 'Goal'
    -#         }
    -#       },
    -#       series: [{
    -#         name: 'Your Distance',
    -#         pointInterval: 24 * 3600 * 1000,
    -#         data: [7900, 8000, 8100, 8500, 7500, 7000, 9000],
    -#         // data: gon.distance.map(function(data){return data.value}),
    -#         color: '#1cab2b',
    -#         zIndex:1,
    -#         }]
    -#     });